CREATE TABLE IF NOT EXISTS CHECKLIST_ITEM (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    completed BOOLEAN DEFAULT FALSE,
    version INT DEFAULT 0
);
